### ISSUE TITLE
js.org

### ISSUE THREAD

**Issue by prasantdev** [BD103/BD103#5]
Hello @BD103 , I saw you were asking if you can host nodejs site withe js.org subdomain. Did you host ?

**Comment by BD103** [comment]
Right now the site is in such development that hosting it would be hasty. I was thinking towards the future.

**Comment by prasantdev** [comment]
> Right now the site is in such development that hosting it would be hasty. I was thinking towards the future.

Oh.. Actually I am trying to use js.org subdomain with nodejs in vercel, but its showing `Invalid Configuration`
![error](https://user-images.githubusercontent.com/67827472/132244344-b95a6bce-6eed-45ea-bf06-a35ff5609cba.jpg)

**Comment by BD103** [comment]
I'm pretty sure what you need to do is add an endpoint that sends the CNAME file.

So requesting `site.com/CNAME` returns `subdomain.js.org`
