### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by darkdarcool** [BD103/BD103#6]
I’ve been working on two big projects, but recently I downloaded a bunch of tools that takes literal days to compile, so I’ve been pretty bored.

So, I was wondering if we could do a collab so I don’t die of boredom.

Open to ideas

I know Java if that helps?

**Comment by BD103** [comment]
Maybe in the future, but I'm working on something big right now. (I've given spoilers already.) I'll keep this in mind in the future. :)
