### ISSUE TITLE
Fork and re-distribution request for Flask-rich

### ISSUE THREAD

**Issue by zyf722** [BD103/BD103#9]
Recently, I have developed a strong interest in both rich and Flask. After a brief online search, I found your logging library, [Flask-rich](https://github.com/BD103/Flask-Rich), and it appears to be precisely what I've been searching for. Allow me to express my sincere respect first.

Having explored the issues in the project repository, I've identified potential solutions for some of them in my personal practice. However, I've also noticed that the repository has been archived since July 3, 2023. Moreover, It seems that there is no explicit license specified for the repository.

I wanted to inquire if it would be possible for me to fork the repository and continue its development based on your code. My intention is to make improvements and potentially publish the enhanced version on PyPI, ensuring that the project remains accessible and valuable to the community.

Could you please clarify the licensing situation for the library and let me know if it would be acceptable for me to proceed with forking and further development?

Thanks for your time.

**Comment by BD103** [comment]
Hi! Thanks for reaching out. If you want to maintain a fork of Flask-Rich, then I would love that. As for the license, I believe the MIT license should work well. Rich is MIT licensed, while Flask is BSD-3 licensed. I can update my copy to include this license before you fork it.

I also have an additional offer, but you don't have to take it.

- I can transfer you the PyPI package namespace so you can publish to it
- Before re-archiving my project, I will link to your project as the official fork

But...

- You must publish using [semantic versioning](https://semver.org/), with your next release being either 0.4.0 or 1.0.0.
- You must add a link back to the original project, saying that you are a fork. The link doesn't need to be big, it just needs to give credit.
- While you maintain the fork, you will review pull requests when you get them. This is in case I ever want to contribute to this project again. You don't need to accept all PRs, but at least look at them.
- If you ever choose to stop maintaining your fork, you will archive it on Github.

That's about it! I hope those terms are reasonable. Please tell me if you agree or want me to change anything, then I can get to work transferring the project.

**Comment by zyf722** [comment]
Thank you for your prompt and positive response!

Generally, the terms sounds completely reasonable to me, and I'm excited to get started on this project. The MIT license works perfectly for me, and I'm grateful for your willingness to update the repository with this license before I proceed with the fork. 

As for the giving-credit link, would it be acceptable to place it within the README file?

**Comment by BD103** [comment]
A link within the README file would be perfect! I will get started migrating the repository. Could you please give me your PyPI username so I can give you ownership?

**Comment by BD103** [comment]
I have committed the MIT license. You can now fork the project. :)

(I'm keeping my source unarchived so I can add a link to your fork once it is created, but I'll archive it again afterwards.)

**Comment by zyf722** [comment]
Great, I have already created the [fork repository](https://github.com/zyf722/Flask-Rich)!

My PyPI username is [MaxMixAlex](https://pypi.org/user/MaxMixAlex/). Honestly, this might be my first publicly released Python package, and I truly appreciate your trust! :grinning:

**Comment by BD103** [comment]
I have updated the repository and re-archived it. I also sent you the invite on PyPI. Thank you for doing this, I look forward to seeing your improvements! :D

**Comment by zyf722** [comment]
I have updated the `README.md` file of the forked repository to include a link back to the original repository, and development for version 0.4.0 will proceed on the new `develop` branch.

Once again, thank you, and you may close this issue for now 😃
